# Data Preprocessing

## Importing the libraries

In [46]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [49]:
dataset = pd.read_csv('Data.csv')

# selecting all columns(features) other than last one(label) 
X = dataset.iloc[:, :-1].values

# selecting the last column only
y = dataset.iloc[:, -1].values

In [50]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


**here we can see all the data from all the columns except the last one**

In [51]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


**here we can see all the data from the last column**

## Taking care of missing data

In [52]:
from sklearn.impute import SimpleImputer

# Imputer(assign) - impute the missing values
# Here strategy used is mean, it can be median or most_frequent or constant depending upon situation
imputer = SimpleImputer(missing_values = np.nan, strategy = 'mean')

# Fit the imputer on X
imputer = imputer.fit(X[:, 1:3])

# Impute all missing values in X
X[:, 1:3] = imputer.transform(X[:, 1:3])

In [53]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


**In this step we can see that all nan values have been replaced with mean of the column** 

## Encoding categorical data

### Encoding the Independent Variable

In [54]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

# Applies transformers to columns of an array or pandas DataFrame.
# OneHotEncoder normalizing the first column country names(index=0)
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')

X = np.array(ct.fit_transform(X))

In [55]:
print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


**Here the Country column is encoded in 0's and 1's**

comparing with CSV file we can find that

* France is encoded as 1 0 0
* Spain is encoded as 0 0 0
* Germany is encoded as 0 0 1

### Encoding the Dependent Variable

In [56]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

# encoding label field in 0's and 1's
y = le.fit_transform(y)

In [57]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


**'NO' has been converted into 0 and 'YES' has been converted into 1**

## Splitting the dataset into the Training set and Test set

In [58]:
from sklearn.model_selection import train_test_split

# If you don't specify the random_state in the code, then every time you run(execute) your code a new random value is generated 
# and the train and test datasets would have different values each time.
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [59]:
print(X_train)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [60]:
print(X_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [61]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [62]:
print(y_test)

[0 1]


## Feature Scaling

In [63]:
from sklearn.preprocessing import StandardScaler

# Standardize features by removing the mean and scaling to unit variance.
sc = StandardScaler()

# applying StandardScaler from 4th column and further, leaving 1st, 2nd and 3rd unchanged 
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])
X_test[:, 3:] = sc.transform(X_test[:, 3:])

In [64]:
print(X_train)

[[0.0 0.0 1.0 -0.19159184384578545 -1.0781259408412425]
 [0.0 1.0 0.0 -0.014117293757057777 -0.07013167641635372]
 [1.0 0.0 0.0 0.566708506533324 0.633562432710455]
 [0.0 0.0 1.0 -0.30453019390224867 -0.30786617274297867]
 [0.0 0.0 1.0 -1.9018011447007988 -1.420463615551582]
 [1.0 0.0 0.0 1.1475343068237058 1.232653363453549]
 [0.0 1.0 0.0 1.4379472069688968 1.5749910381638885]
 [1.0 0.0 0.0 -0.7401495441200351 -0.5646194287757332]]


In [65]:
print(X_test)

[[0.0 1.0 0.0 -1.4661817944830124 -0.9069571034860727]
 [1.0 0.0 0.0 -0.44973664397484414 0.2056403393225306]]
